networks:
  net:
volumes:
  problems:

services:
  phpmyadmin:
    image: phpmyadmin
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      MYSQL_ROOT_PASSWORD: root
    networks:
      - net
    ports:
      - 8080:80

  db:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: nboj
    networks:
      - net
    ports:
      - 3306:3306
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p$$MYSQL_ROOT_PASSWORD"]
      timeout: 20s
      retries: 10

  shell:
    image: nboj
    networks:
      - net
    volumes:
      - .:/nboj
      - problems:/problems
    entrypoint: ["bash"]
    stdin_open: true
    tty: true
    depends_on:
      - db

  bridge:
    image: nboj
    networks:
      - net
    volumes:
      - .:/nboj
    command: ["runbridged"]
    stdin_open: true
    tty: true
    depends_on:
      db:
        condition: service_healthy

  site:
    image: nboj
    networks:
      - net
    volumes:
      - .:/nboj
      - problems:/problems
    command: ["runserver", "0.0.0.0:8000"]
    stdin_open: true
    tty: true
    ports:
      - 8000:8000
    depends_on:
      db:
        condition: service_healthy

  judge:
    build:
      context: https://github.com/DMOJ/judge-server.git
      dockerfile: .docker/tier1/Dockerfile
      args:
        TAG: master
    networks:
      - net
    volumes:
      - problems:/problems
    cap_add:
      - SYS_PTRACE
    depends_on:
      db:
        condition: service_healthy