# Generated by Django 4.1.3 on 2022-11-10 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='code',
        ),
        migrations.AddField(
            model_name='task',
            name='index',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
    ]
