# Generated by Django 4.1.3 on 2022-11-11 10:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0003_task_attachments_alter_task_contest_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='attachments',
        ),
    ]
