# Generated by Django 4.1.3 on 2022-11-13 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0005_contest_end_time_contest_start_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='source',
            field=models.TextField(default='', max_length=65536, verbose_name='source code'),
            preserve_default=False,
        ),
    ]
