# Generated by Django 4.1.3 on 2022-11-17 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0009_submission_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='non_scaled_points',
            field=models.FloatField(db_index=True, default=0),
        ),
        migrations.AddField(
            model_name='submission',
            name='non_scaled_total',
            field=models.FloatField(db_index=True, default=0),
        ),
        migrations.AddField(
            model_name='task',
            name='points',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
