# Generated by Django 4.1.3 on 2022-11-18 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0010_submission_non_scaled_points_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='participation',
            constraint=models.UniqueConstraint(fields=('contest', 'user'), name='unique_participant'),
        ),
    ]
