# Generated by Django 4.1.3 on 2022-11-18 19:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0011_participation_unique_participant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='contest',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='judge.contest'),
        ),
    ]
