# Generated by Django 4.1.3 on 2022-11-19 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0012_alter_task_contest'),
    ]

    operations = [
        migrations.AddField(
            model_name='attachment',
            name='fontawesome_icon_class',
            field=models.CharField(default='fa-solid fa-file', max_length=255),
        ),
        migrations.AddField(
            model_name='task',
            name='allowed_languages',
            field=models.ManyToManyField(to='judge.language'),
        ),
    ]
