# Generated by Django 4.1.3 on 2022-11-22 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0013_attachment_fontawesome_icon_class_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='attachment',
            constraint=models.UniqueConstraint(fields=('task', 'name'), name='unique_attachment_name'),
        ),
    ]
