# Generated by Django 4.1.3 on 2022-11-22 18:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0014_attachment_unique_attachment_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='language',
            name='extension',
        ),
        migrations.RemoveField(
            model_name='language',
            name='short_name',
        ),
        migrations.RemoveField(
            model_name='language',
            name='template',
        ),
    ]
