# Generated by Django 4.1.3 on 2022-11-22 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0015_remove_language_extension_remove_language_short_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='statement_file',
        ),
        migrations.AddField(
            model_name='attachment',
            name='is_statement_file',
            field=models.BooleanField(default=False),
        ),
    ]
