# Generated by Django 4.1.3 on 2022-11-24 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0016_remove_task_statement_file_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attachment',
            name='path',
            field=models.CharField(max_length=255),
        ),
    ]
