# Generated by Django 4.1.3 on 2022-11-25 18:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0017_alter_attachment_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='cases',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='submission',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='judge.task', verbose_name='task'),
        ),
    ]
